version: '3.7'
services:
  mongo:
    image: mongo
    hostname: mongo
    ports:
      - '27017-27019:27017-27019'
  app:
    build: .
    volumes:
      - ./:/home/app
      - /home/app/node_modules
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - mongo
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017/data
